### ISSUE TITLE
pnpm serve error

### ISSUE THREAD

**Issue by everpan** [IceWhaleTech/CasaOS-App-UI#99]
> vue-cli-service serve --mode dev && tsc

 INFO  Starting development server...
 10% building 1/1 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:452:10)
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:484:5
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:343:12
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/graceful-fs@4.2.11/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
 10% building 1/4 modules 3 active ...js?http://192.168.199.241:8080&sockPath=/sockjs-nodenode:internal/crypto/hash:79                             
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:452:10)
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:484:5
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/webpack@4.36.0/node_modules/webpack/lib/NormalModule.js:343:12
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/graceful-fs@4.2.11/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.
/Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_eslint@6.8.0_typescript@5.4.5_vue-template-compiler@2.7.16_webpack@4.36.0/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47
                                closedError = new RpcIpcMessagePortClosedError_1.RpcIpcMessagePortClosedError(`Cannot send the message - the message port has been closed for the process ${process.pid}.`);
                                              ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 23459.
    at /Users/ever/git/learn/web/CasaOS-App-UI/node_modules/.pnpm/fork-ts-checker-webpack-plugin@5.2.1_eslint@6.8.0_typescript@5.4.5_vue-template-compiler@2.7.16_webpack@4.36.0/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v20.15.0

**Comment by jerrykuku** [comment]
Please set env before serve `export NODE_OPTIONS=--openssl-legacy-provider`
